### ISSUE TITLE
About converting the models for Torch to the models for PyTorch

### ISSUE THREAD

**Issue by SuhyeonHa** [naoto0804/pytorch-AdaIN#21]
When I type this command,
`python torch_to_pytorch.py --model models/vgg_normalised.t7`

It produces errors as below.

```
Traceback (most recent call last):
  File "torch_to_pytorch.py", line 321, in <module>
    torch_to_pytorch(args.model, args.output)
  File "torch_to_pytorch.py", line 266, in torch_to_pytorch
    model = load_lua(t7_filename, unknown_classes=True)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 608, in load_lua
    return reader.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 571, in read_table
    k = self.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 572, in read_table
    v = self.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 573, in read_table
    table[k] = v
TypeError: unhashable type: 'list'
```

Also If I type the next line,
`python torch_to_pytorch.py --model models/decoder.t7`

It shows like this.
```
Traceback (most recent call last):
  File "torch_to_pytorch.py", line 321, in <module>
    torch_to_pytorch(args.model, args.output)
  File "torch_to_pytorch.py", line 266, in torch_to_pytorch
    model = load_lua(t7_filename, unknown_classes=True)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 608, in load_lua
    return reader.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 571, in read_table
    k = self.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 572, in read_table
    v = self.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 593, in read
    return self.read_object()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 546, in read_object
    return reader_registry[cls_name](self, version)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 318, in wrapper
    obj = build_fn(reader, version)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 243, in read_nn_class
    attributes = reader.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 595, in read
    return self.read_table()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 523, in wrapper
    result = fn(self, *args, **kwargs)
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 572, in read_table
    v = self.read()
  File "C:\Users\a\Anaconda3\envs\AdaIN_env\lib\site-packages\torch\utils\serialization\read_lua_file.py", line 598, in read
    "corrupted.".format(typeidx))
torch.utils.serialization.read_lua_file.T7ReaderException: unknown type id -1050704824. The file may be corrupted.

```
It will be so thankful if you reply to the issue. :)

**Comment by naoto0804** [comment]
I haven't seen such issue before. Just to make sure, which PyTorch version are you using? (c.f., #20 )

**Comment by SuhyeonHa** [comment]
I used Windows10, WSL(Windows Subsystem for Linux) and PyTorch 0.4.1.

**Comment by ArturoDeza** [comment]
I've been having the same problem. Can someone upload a direct link to the converted models so that we can run the code with PyTorch 1.1?

**Comment by Serbernari** [comment]
And same problem again, still no solution?

**Comment by naoto0804** [comment]
@SuhyeonHa I don't have windows environment, so I cannot test it, sorry.

For convenience, I share the converted version of the models. Please try it and let me know if something wrong happened. (There might need some modifications for exporting 0.4 to 1.0 or 1.1,  but I don't have enough time to test it all)
[vgg_normalized.pth](https://drive.google.com/open?id=108uza-dsmwvbW2zv-G73jtVcMU_2Nb7Y)
[decoder.pth](https://drive.google.com/open?id=1w9r1NoYnn7tql1VYG3qDUzkbIks24RBQ)

**Comment by sunyuxiu** [comment]
@naoto0804 Hi, thanks for the excellent work!
But could you please release the models ([vgg_normalised.pth, decoder.pth]) on OneDrive, too? I can't download the google or dropbox link in China...
Thanks very much!

**Comment by naoto0804** [comment]
@sunyuxiu OK, can you tell me the email address to send the link?

**Comment by sunyuxiu** [comment]
@naoto0804 2787228395@qq.com

**Comment by naoto0804** [comment]
Hmm, I'm using my company's OneDrive, and it does not allow me to share the link to addresses ended with qq.com; do you have another address?

**Comment by sunyuxiu** [comment]
@naoto0804 What about rogers_sun@foxmail.com?

**Comment by naoto0804** [comment]
It does not work; wait a moment, I'll host a server temporarily

**Comment by sunyuxiu** [comment]
@naoto0804 OK.Thank you!

**Comment by naoto0804** [comment]
`https://www.hal.t.u-tokyo.ac.jp/~inoue/projects/tmp/decoder.pth`
`https://www.hal.t.u-tokyo.ac.jp/~inoue/projects/tmp/vgg_normalized.pth`

**Comment by naoto0804** [comment]
@sunyuxiu  Let me know when you finish downloading

**Comment by sunyuxiu** [comment]
@naoto0804 The decoder.pth model is OK to download.But the vgg pth is 404 Not Found.Sorry to reply too late.

**Comment by naoto0804** [comment]
I fixed the weight. Could you try it again?

**Comment by sunyuxiu** [comment]
@naoto0804 It is still  404 Not Found.Not Found
The requested URL /~inoue/projects/tmp/vgg_normalized.pth was not found on this server.

**Comment by naoto0804** [comment]
I found there is a typo;
`https://www.hal.t.u-tokyo.ac.jp/~inoue/projects/tmp/vgg_normalised.pth`

**Comment by sunyuxiu** [comment]
@naoto0804 Thank you.I finished.
